### ISSUE TITLE
books are fetched again when going back to home

### ISSUE THREAD

**Issue by ahmedkhaled1994** [MaheedHatem/Raf#5]
books need to be saved and retrieved from saved instances

**Comment by ahmedkhaled1994** [comment]
happened only once

**Comment by taha-ibrahim** [comment]
each time you create new home fragment or category fragment or wishlist fragment, i think we should create it once only and start instead of recreation

**Comment by ahmedkhaled1994** [comment]
@taha-ibrahim garrab keda delwa2ty
